// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function QueryCategories():Promise<Array<string>>;

export function QueryNovelById(arg1:string):Promise<models.Novel>;

export function QueryNovels(arg1:main.NovelQuery,arg2:number,arg3:number):Promise<main.NovelResult>;

export function QueryNovelsCount():Promise<number>;
