// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function Greet(arg1:string):Promise<string>;

export function QueryNovels(arg1:main.NovelQuery,arg2:number,arg3:number):Promise<Array<models.Novel>>;
