// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function QueryCategories() {
  return window['go']['main']['App']['QueryCategories']();
}

export function QueryNovels(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryNovels'](arg1, arg2, arg3);
}

export function QueryNovelsCount() {
  return window['go']['main']['App']['QueryNovelsCount']();
}
